# Generated by Django 4.2.1 on 2023-06-04 20:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+375336314010", max_length=128, region="BY"
            ),
            preserve_default=False,
        ),
    ]
